
TYPE
	typFacility : 	STRUCT 
		Ident : ARRAY[0..LOGBOOK_FACILITIES_MAX]OF UDINT;
		RecordIDLatest : ARRAY[0..LOGBOOK_FACILITIES_MAX]OF UDINT;
		RecordIDOld : ARRAY[0..LOGBOOK_FACILITIES_MAX]OF UDINT;
		RecordIDIsLast : ARRAY[0..LOGBOOK_FACILITIES_MAX]OF BOOL;
		RecordID : ARRAY[0..LOGBOOK_FACILITIES_MAX]OF UDINT;
		CntFacility : USINT;
	END_STRUCT;
END_TYPE
